### ISSUE TITLE
Feature request: display message when focus (-f) is not passed.

### ISSUE THREAD

**Issue by erikeah** [vbauerster/kampliment#15]
### Current behavior:

Once kamp is initialized in kakoune and we have a shell terminal connected to kamp, it's possible to execute `kamp edit` and the kakoune instance will display the selected buffer. **However in the bash terminal we have not any feedback.**

### Proposal:
Print a message to let user know that the file has been open in client X session Y.

**Comment by vbauerster** [comment]
Can you pls check branch `req-15` if it works for you?

**Comment by erikeah** [comment]
Thank you @vbauerster! `req-15` fulfill the feature request.
