### ISSUE TITLE
kamp-files opens *stdin* buffer, secondary selections are listed as strings in *stdin* buffer

### ISSUE THREAD

**Issue by jtrv** [vbauerster/kampliment#8]
Multiple files example:
![termtosvg_4afond42](https://user-images.githubusercontent.com/46337843/176812407-2ea4900d-a9f0-4d83-a1c0-65406550a769.svg)
Single file example:
![termtosvg_49gjfjqf](https://user-images.githubusercontent.com/46337843/176814907-5cc72483-1b74-4a97-90c0-508de880bb71.svg)

**Comment by vbauerster** [comment]
Just for notes, result is the same as with `echo Cargo.lock | kak` command.
Presumably that script passes args files like aforementioned command.
